### ISSUE TITLE
Error [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [WanionCane/WanionLib#6]
MC 1.12.2. WanionLib 1.5.
Lines 23662-23726 - https://gist.github.com/kellixon/4ede55e99ef4e7fb8cdd19e346d51062

**Comment by WanionCane** [comment]
I couldn't read it.
it says:
> Not Found
> Error 404

**Comment by kellixon** [comment]
https://yadi.sk/d/nf-A9VLE3Uvn5R

**Comment by kellixon** [comment]
Update url!

**Comment by WanionCane** [comment]
I took a look, and I couldn't find any relation with WanionLib on this log.

**Comment by kellixon** [comment]
As there is no error, the string specified? Download this is file - Lines 23662-23726!
`[16:54:16] [main/ERROR] [wanionlib]: UniDictSomething really bad happened on Integration at load stage POST_INIT
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: cofh/thermalexpansion/util/managers/machine/FurnaceManager$ComparableItemStackFurnace
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.util.concurrent.FutureTask.report(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.util.concurrent.FutureTask.get(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.lib.module.AbstractModule.start(AbstractModule.java:55)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.lib.module.ModuleHandler.lambda$startModules$0(ModuleHandler.java:39)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.lang.Iterable.forEach(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.lib.module.ModuleHandler.startModules(ModuleHandler.java:31)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.unidict.proxy.CommonProxy.postInit(CommonProxy.java:85)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.unidict.proxy.ClientProxy.postInit(ClientProxy.java:34)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at wanion.unidict.UniDict.postInit(UniDict.java:98)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:54:16] [main/INFO] [STDERR]: [wanion.lib.module.AbstractModule:start:59]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: cofh/thermalexpansion/util/managers/machine/FurnaceManager$ComparableItemStackFurnace
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at wanion.unidict.integration.TEIntegration.fixRedstoneFurnaceRecipes(TEIntegration.java:146)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at wanion.unidict.integration.TEIntegration.call(TEIntegration.java:39)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at wanion.unidict.integration.TEIntegration.call(TEIntegration.java:25)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Thread.run(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: cofh.thermalexpansion.util.managers.machine.FurnaceManager$ComparableItemStackFurnace
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 7 more
[16:54:16] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException`

**Comment by WanionCane** [comment]
[this](https://minecraft.curseforge.com/projects/unidict/files/2563162) should fix it.
